### ISSUE TITLE
Error after session timeout

### ISSUE THREAD

**Issue by dpi209** [CosmoQuestX/CSB7.0#102]
** Bug report summary **
After session has timed out, and the user selects 'User' ==> 'My profile', one gets the following error;
"Fatal error: require_once(): Failed opening required '/var/www/html/csb/csb-content/templates/login.php' (include_path='.:/usr/share/php') in /var/www/html/CSB7.0/csb/csb-accounts/profile.php on line 38"

** Steps To Reproduce **
Wait until session timeout and then select the drop-down menu and select 'My profile'.

**OS / Browser / Resolution **
browser-agnostic

**Comment by dpi209** [comment]
This error was reported by helgesnutten on discord.

**Comment by KeeperOfMaps** [comment]
There doesn't appear to be a `login.php` in `/csb/csb-content/templates/`. There is a `mustLogin-template.php`, however.

**Comment by dpi209** [comment]
Yes, it appears to have been forgotten on a change. CSB notices the session has expired and requests a login but jumps to the wrong page.
