### ISSUE TITLE
Javascript - page is reloaded when closing mapping app

### ISSUE THREAD

**Issue by aarbrown** [CosmoQuestX/CSB7.0#16]
After launching the mapping app, when you click the X button to exit the app the entire page reloads.  This should instead reapply the `display: none;` style to the cq-mapping-tool div and reset the state of the csbApp (not sure if that's necessary since we're creating a new csbapp when we launch the app??)

**Comment by eladavron** [comment]
Solved in an upcoming PR (currently downstream [here](https://github.com/eladavron/CSB7.0/commit/0a0e79883be80bc607b9aa3e35e2fda0286c2fd3))

**Comment by dpi209** [comment]
This is confirmed squashed.
