### ISSUE TITLE
PHP - highlight correct nav item

### ISSUE THREAD

**Issue by aarbrown** [CosmoQuestX/CSB7.0#17]
Once the user has navigated to a new page (i.e. by clicking Bennu Mapper link), the Home nav item is still highlighted.  The nav item that corresponds to the current page should instead be highlighted.

**Comment by dpi209** [comment]
Already generating the nav links from the database but apparently forgot to comment accordingly. That fix is in api_build, currently

**Comment by dpi209** [comment]
Fix merged into master on 27 Jun 2020
