### ISSUE TITLE
Make last page of installer prettier. 

### ISSUE THREAD

**Issue by starstryder** [CosmoQuestX/CSB7.0#28]
- Don't actually need to show all tables that work. Only show errors.
- Add a header
- Be super obnoxious about write down password

**Comment by dpi209** [comment]
The first bullet point is already done, silently and coincidentally, with a different fix.

**Comment by starstryder** [comment]
I thought this had been done, but somehow saw them again. Must have a syncing issue on my end :-/

**Comment by dpi209** [comment]
Nah, that PR is still open, just thought I could document that in the issue before anybody puts work into this.

**Comment by submitteddenied** [comment]
Hello! I'm taking a swing at this and hope to have a PR up later today

**Comment by starstryder** [comment]
wow. That looks sweet. merging in now.

**Comment by dpi209** [comment]
I believe this issue can be closed?
