### ISSUE TITLE
Installer DB test: Create empty div that alert appears in so no resizing

### ISSUE THREAD

**Issue by starstryder** [CosmoQuestX/CSB7.0#37]
Currently the "Everything works" alert is causing the installer window to resize.
It would be better to add an alerts div to that window that is empty and has its size set and then write into that empty div so nothing changes size.

**Comment by eladavron** [comment]
I could not reproduce the issue.
Could this be browser-specific?

**Comment by dpi209** [comment]
Was changed in above merge, but you not being able to reproduce probably means that it can be considered fixed ;)
