### ISSUE TITLE
Mobile Navigation Page Unclickable

### ISSUE THREAD

**Issue by YouTubeAdmin** [CosmoQuestX/CSB7.0#38]
The navigation burger button [three horizontal lines] is  unclickable  / disabled on mobile.

Browser: Safari
OS: iPhone 8

**Comment by colmeye** [comment]
What branch is this issue happening on? Also what browser are you using? the sandbox page works fine on my phone and my browsers

**Comment by YouTubeAdmin** [comment]
The issue has since resolved itself! (I swear it happened)
