### ISSUE TITLE
Installer check directory

### ISSUE THREAD

**Issue by starstryder** [CosmoQuestX/CSB7.0#55]
If you try and run open the uninstalled site in a random directory it will not find the installer correctly. Need to try and find the base url and use it to go to the installer.

**Comment by dpi209** [comment]
Sorry, I got an error briefly but can't repro, so nevermind me reopening.

**Comment by dpi209** [comment]
Now I can repro. Tried a fresh install today, and: 
![grafik](https://user-images.githubusercontent.com/54415194/79073484-34012000-7ce7-11ea-9f79-dfec42e0dcb6.png)

**Comment by dpi209** [comment]
However: 
![grafik](https://user-images.githubusercontent.com/54415194/79073503-52671b80-7ce7-11ea-9277-8f22cc33b1a6.png)
