### ISSUE TITLE
Login window closes when ' is present in the username

### ISSUE THREAD

**Issue by eladavron** [CosmoQuestX/CSB7.0#62]
# Expected behavior
1.  In the login window, type an invalid string in the username containing an apostrophe
2. Click on "Login"
3. The page should reload with the login window open and an error message saying "Login failed: user not found"

# Actual behavior
The page reloads but the login window is closed. It may appear as if it has succeeded, but clicking "login" again will pop up the window with the error message expected before.

![2020-03-29_13-29-10](https://user-images.githubusercontent.com/5508836/77847077-f8cd0000-71c2-11ea-9f82-d67355e80bec.gif)

# Bonus
Should we even allow submission in cases if invalid characters, or should we prevent it on the frontend using form validation?

**Comment by eladavron** [comment]
Update:
This happens because the code in index.php then compiles to:

```js
if ('Login failed: User CodeHerder' not found' !== '') {
    $('#loginModal').removeClass('fade');
    $('#loginModal').modal('show');
}
```
And the apostrophe breaks the javascript.
Escaping it on the PHP side should solve it, but it shouldn't be allowed to be submitted int the first place.

**Comment by dpi209** [comment]
Tested and confirmed squashed.
