### ISSUE TITLE
Login shouldn't specify whether username or password is incorrect

### ISSUE THREAD

**Issue by eladavron** [CosmoQuestX/CSB7.0#65]
Security through obscurity dictates that "Wrong username" and "wrong password" should be the same message so that an attacker couldn't determine if a username exists or not.

**Comment by dpi209** [comment]
I'm not a fan of security by obscurity, to be honest. I'd rather just be secure but user-friendly. 
Can't you still determine whether a username exists if you just test with a password that is pretty much guaranteed not to be used, like a random 24-byte string, or in our case even a null password?

**Comment by eladavron** [comment]
I don't see how, but it is a design question.
We should defer to @starstryder 's decision. On whether or not they should be merged.

**Comment by dpi209** [comment]
Yeah. I get what you're saying now. 
Can I propose that we still keep the cases and only adjust the output? 
Let's say if we wanted to have an admin panel in the future that shows the last 25 unsuccessful logins, it'd be easier (plus, I'm lazy).

**Comment by eladavron** [comment]
That's reasonable, that was my original implementation but I figured it's code duplication and I tried to make it more generic.
That said, for what you proposed, it could still be done with a generic singular handler.
Let's discuss it further on Discord tomorrow.

**Comment by dpi209** [comment]
Closing, since PR has been merged.
