### ISSUE TITLE
Unreachable or Non-Existent Script in Profile

### ISSUE THREAD

**Issue by YouTubeAdmin** [CosmoQuestX/CSB7.0#68]
`csb-accounts/profile.php` calls for a non-existent or unreachable `csb-content/js/profile.js` returning a `net::ERR_ABORTED 404 (Not Found)` error in the Dev Console.

**Browser:** *Google Chrome*
**OS:** *Windows 10*

**Comment by dpi209** [comment]
Fixed in #67
