### ISSUE TITLE
Reset Password doesn't work

### ISSUE THREAD

**Issue by YouTubeAdmin** [CosmoQuestX/CSB7.0#69]
When you use `csb-accounts/rescue.php`, you receive this error:
`authentication failure [SMTP: Invalid response code received from server (code: 535, response: Authentication failed: The provided authorization grant is invalid, expired, or revoked)]`

**Browser:** *Google Chrome*
**OS:** *Windows 10*

**Comment by dpi209** [comment]
This was a password problem on a test server.
