### ISSUE TITLE
Label Enhancement (aka Nit Pick)

### ISSUE THREAD

**Issue by YouTubeAdmin** [CosmoQuestX/CSB7.0#71]
**Nit Picking:**
Change `csb-accounts/profile.php` right text to this *(sorry if that sounds rude)*:
Your privacy matters! Our team *of* programmers ~~do~~ *(technically correct but not used much, at least in my area)* have access to this information, but the only thing that can be publicly seen is your username. We will, with permission only, use your first and last name to give you credit for things you accomplish.

**Comment by dpi209** [comment]
Fixed in #67
