### ISSUE TITLE
Project name variable needed

### ISSUE THREAD

**Issue by KeeperOfMaps** [CosmoQuestX/CSB7.0#96]
It would be useful to have a variable that holds the name of the project for use in things like the rescue email Subject and signature in the body.

ref: Issue #91

**Comment by dpi209** [comment]
For what would the project name be useful in the rescue email?
There are no project-specific emails (yet).

**Comment by KeeperOfMaps** [comment]
It would be useful for the signature of the rescue email. Also, the subject is hard coded with the name "CosmoQuest ...", so that should also be definable.

**Comment by dpi209** [comment]
That could probably be changed to 
`$page_title. "Password reset". `
Rescue emails are site-specific, not project-specific.

**Comment by KeeperOfMaps** [comment]
Sorry, my bad. I used the term "project" referring to the whole CSB, not one of the specific mappers. I meant that the email needs a variable for the name of the organization.

**Comment by dpi209** [comment]
$SITE_NAME should be set, so you should be able to use it in the rescue email. Can you test that and see if it is what you were thinking of?

**Comment by KeeperOfMaps** [comment]
Ah, that sounds like what I need. I'll check it out. Thanks!
